spring:
   application:
      name: eureka_server_02
   security:
    user:
      name: eureka
      password: 123456
    
server:
   port: 8050
   
   
eureka:
   instance:
      hostname: eureka_server_02
   client:
      serviceUrl:
         defaultZone: http://eureka:123456@192.168.0.10:8050/eureka/
      register-with-eureka: false
      fetch-registry: false
   server:
    enable-self-preservation: false