spring:
   application:
      name: eureka_server_02
server:
   port: 8051
   
eureka:
   instance:
      hostname: eureka_server_02
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8050/eureka/